### PR TITLE
Structure: allow to skip defaults per structure

### PR DESCRIPTION
**Pull request by f3l1x**
- new feature? yes
- BC break? no

It allows to skip defaults only for some structures.

### CODE REVIEW

**Comment by dg** [comment]
Perhaps a very similar result can be achieved with `->required (false)`, what do you think? Related to #17  and 27e57b12e64

**Comment by f3l1x** [comment]
Thanks. Looks good. :-)

**Comment by dg** [comment]
But maybe not :-) I don't know exactly what your intention is.

**Comment by f3l1x** [comment]
I think it's ok, my intention was to disable default values for nested structure. :-)

**Pull request closed without merging**
