### PR TITLE
Assert with optinal description #7

### PR DESCRIPTION
**Pull request by integer**
- new feature #7 
- BC break? no

With this PR you can add description to your asserts and this description will be printed in error messages.

```php
$schema = Expect::string()
        ->assert('ctype_digit', 'Is number')
        ->assert(function ($s) { return strlen($s) >= 3; }, 'Minimal lenght');
```

### CODE REVIEW

**Comment by dg** [comment]
It could still be implemented in an alternative way, but I don't know what's better.

```php
$schema = Expect::arrayOf('string')
	->assert(function ($v) { 
		if (count($v) % 2 === 0) { // count must be even number
			throw new AssertException('Even items in array');
		}
	}); 
```

**Comment by mabar** [comment]
I would like exception, it allows non-statical error messages

**Comment by dg** [comment]
After experience with forms and `addRule()` I would prefer exceptions today.

**Comment by integer** [comment]
Exceptions requires more writing, but you can prepare better message. I will try exceptions in my project. Thank you for hint.

**Pull request merged**
